nav:
  Home: /
  About: /about/
  Writing: QM36
  Projects: http://github.com/probberechts

projects_url: https://github.com/QM36

customize:
    gravatar:
        email: 18791767622@163.com
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/QM36
        twitter: /
        facebook: /
        linkedin: /
        zhihu: https://www.zhihu.com/people/qu-meng-55/activities
        email: 18791767622@163.com
    show_all_posts: false
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
